config/routes.rb
Autolab3::Application.routes.draw do
  root "courses#index"

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks",
                                    registrations:      "registrations" },
                     path_prefix: "auth"

  get "contact", to: "home#contact"

  namespace :home do
    if Rails.env == "development"
      match "developer_login", via: [:get, :post]
    end
    get "error"
    get "error_404"
    get "no_user"
  end

  resource :admin do
    match "email_instructors", via: [:get, :post]
  end

  resources :users do
    get "admin"
  end

  resources :courses, param: :name do
    resources :schedulers
    resources :jobs, only: :index do
      get "getjob", on: :member

      collection do
        get "tango_status"
        get "tango_data"
      end
    end
    resources :announcements, except: :show
    resources :attachments

    resources :assessments, param: :name, except: :update do
      resource :autograder, except: [:new, :show]
      resources :assessment_user_data, only: [:edit, :update]
      resources :attachments
      resources :extensions, only: [:index, :create, :destroy]
      resources :groups, except: :edit do
        member do
          post "add"
          post "join"
          post "leave"
        end

        post "import", on: :collection
      end
      resources :problems, except: [:index, :show]
      resource :scoreboard, except: [:new] do
        get "help", on: :member
      end
      resources :submissions do
        resources :annotations, only: [:create, :update, :destroy]
        resources :scores, only: [:create, :show, :update]

        member do
          get "destroyConfirm"
          get "download"
          get "listArchive", as: :list_archive
          get "view"
        end

        collection do
          get "downloadAll"
          get "missing"
        end
      end

      member do
        match "bulkGrade", via: [:get, :post]
        post "bulkGrade_complete"
        get "bulkExport"
        get "releaseAllGrades"
        get "releaseSectionGrades"
        get "viewFeedback"
        get "reload"
        get "statistics"
        get "withdrawAllGrades"
        get "export"
        patch "edit/*active_tab", action: :update
        get "edit/*active_tab", action: :edit
        post "handin"
        get "history"
        get "viewGradesheet"
        get "writeup"
        get "handout"

        # autograde actions
        post "autograde_done"
        post "regrade"
        post "regradeBatch"
        post "regradeAll"

        # SVN actions
        get "admin_svn"
        post "import_svn"
        post "set_repo"

        # gradesheet ajax actions
        post "quickSetScore"
        post "quickSetScoreDetails"
        get "quickGetTotal"
        get "score_grader_info"
        get "submission_popover"

        # remote calls
        match "local_submit", via: [:get, :post]
        get "log_submit"
      end

      collection do
        get "installAssessment"
        post "importAssessment"
        post "importAsmtFromTar"
      end
    end

    resources :course_user_data do
      resource :gradebook, only: :show do
        get "bulkRelease"
        get "csv"
        get "invalidate"
        get "statistics"
        get "student"
        get "view"
      end

      member do
        get "destroyConfirm"
        match "sudo", via: [:get, :post]
        get "unsudo"
      end
    end

    member do
      get "bulkRelease"
      get "downloadRoster"
      match "email", via: [:get, :post]
      get "manage"
      get "moss"
      get "reload"
      match "report_bug", via: [:get, :post]
      post "runMoss"
      get "sudo"
      match "uploadRoster", via: [:get, :post]
      get "userLookup"
      get "users"
    end
  end
end

app/models/scheduler.rb
class Scheduler < ActiveRecord::Base
  trim_field :action
  self.table_name = :scheduler
  belongs_to :course

  validates_numericality_of :interval
  validates_presence_of :action
  validates_associated :course
end

app/controllers/schedulers_controller.rb
##
# Schedulers are used by like buflab and bomblab and that's it.  Tasks don't actually
# get accurately scheduled, but with each request, we check all schedulers, and if one
# hasn't ran in more than its period's time, it's function is run.  This is awful.
#
class SchedulersController < ApplicationController
    rescue_from ActionView::MissingTemplate do |exception|
      redirect_to("/home/error_404")
  end
  action_auth_level :index, :instructor
  def index
    @schedulers = Scheduler.where(course_id: @course.id)
  end

  action_auth_level :show, :instructor
  def show
    @scheduler = Scheduler.find(params[:id])
  end

  action_auth_level :new, :instructor
  def new
  end

  action_auth_level :create, :instructor
  def create
    @scheduler = @course.scheduler.new(scheduler_params)
    if @scheduler.save
      flash[:success] = "Scheduler created!"
      redirect_to(course_schedulers_path(@course)) && return
    else
      flash[:error] = "Create failed! Pleaes check all fields."
      redirect_to(action: "new") && return
    end
  end

  action_auth_level :edit, :instructor
  def edit
    @scheduler = Scheduler.find(params[:id])
  end

  action_auth_level :update, :instructor
  def update
    @scheduler = Scheduler.find(params[:id])
    if @scheduler.update(scheduler_params)
      flash[:success] = "Edit success!"
      redirect_to(course_schedulers_path(@course)) && return
    else
      flash[:error] = "Schedular Edit failed! Please check your fields."
      redirect_to(action: "edit") && return
    end
  end

  action_auth_level :destroy, :instructor
  def destroy
    @scheduler = Scheduler.find(params[:id])
    @scheduler.destroy # boo
    redirect_to(action: "index") && return
  end

private

  def scheduler_params
    params.require(:scheduler).permit(:action, :next, :interval)
  end
end

app/helpers/scheduler_helper.rb
module SchedulerHelper
end

app/views/schedulers/create.html.erb
<h1>Scheduler#create</h1>
<p>Find me in app/views/scheduler/create.html.erb</p>

app/views/schedulers/destroy.html.erb
<h1>Scheduler#destroy</h1>
<p>Find me in app/views/scheduler/destroy.html.erb</p>

app/views/schedulers/edit.html.erb
<% content_for :javascripts do %>
  <%= javascript_include_tag "initialize_datetimepickers" %>
<% end %>

<h2>Editing scheduler</h2>

<%= form_for @scheduler, :url=>{:action=>"update"}, :method=>"patch", builder: FormBuilderWithDateTimeInput do |f| %>
  <%= f.error_messages %>
  <%= f.text_field :action, help_text: "  ", placeholder: "(scheduler action)" %>
  <%= f.datetime_select :next, step: 1 %>
  <%= f.text_field :interval , placeholder: "(in seconds)" %>
  <div class="action_buttons">
    <%= f.submit "Update" , {:class=>"btn primary"} %>
  </div>
<% end %>

<%= link_to 'Show', {:action=>"show",:id=>@scheduler.id} %> |
<%= link_to 'Index', {:action=>"index"} %>

app/views/schedulers/index.html.erb
<h2>Manage Schedulers</h2>
<i>It is currently <%= Time.now() %></i>

<p>
<%= link_to 'Create New Scheduler', new_course_scheduler_path(@course) %>
</p>
<table class="prettyBorder" >
  <tr>
    <th>Action</th>
    <th>Next</th>
    <th>Interval</th>
  </tr>

<% for scheduler in @schedulers %>
  <tr>
    <td><%=h scheduler.action %></td>
    <td><%=h scheduler.next %></td>
    <td><%=h scheduler.interval %></td>
    <td><%= link_to 'Show', {:action=>"show",:id=>scheduler.id} %>
    <%= link_to 'Edit', edit_course_scheduler_path(@course, scheduler) %>
    <%= link_to 'Destroy', course_scheduler_path(@course, scheduler), method: "delete", data: {confirm: 'Are you sure?'} %></td>
  </tr>
<% end %>
</table>

<br />

app/views/schedulers/new.html.erb
<% content_for :javascripts do %>
  <%= javascript_include_tag "initialize_datetimepickers" %>
<% end %>
<h2>New scheduler</h2>

<%= form_for :scheduler, :url=>{:action=>"create"}, builder: FormBuilderWithDateTimeInput do |f| %>
  <%= f.error_messages %>
  <%= f.text_field :action, help_text: "  ", placeholder: "(scheduler action)" %>
  <%= f.datetime_select :next, step: 1 %>
  <%= f.text_field :interval , placeholder: "(in seconds)" %>
  <div class="action_buttons">
    <%= f.submit "Create" , {:class=>"btn primary"} %>
  </div>
  
<% end %>

<%= link_to 'Back', :action=>"index" %>

app/views/schedulers/show.html.erb
<p>
  <b>Action:</b>
  <%=h @scheduler.action %>
</p>

<p>
  <b>Next:</b>
  <%=h @scheduler.next %>
</p>

<p>
  <b>Interval:</b>
  <%=h @scheduler.interval %>
</p>


<%= link_to 'Edit', {:action=>"edit",:id=>@scheduler.id} %> |
<%= link_to 'Back', {:action=>"index"} %>