config/routes.rb
Autolab3::Application.routes.draw do
  root "courses#index"

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks",
                                    registrations:      "registrations" },
                     path_prefix: "auth"

  get "contact", to: "home#contact"

  namespace :home do
    if Rails.env == "development"
      match "developer_login", via: [:get, :post]
    end
    get "error"
    get "error_404"
    get "no_user"
  end

  resource :admin do
    match "email_instructors", via: [:get, :post]
  end

  resources :users do
    get "admin"
  end

  resources :courses, param: :name do
    resources :schedulers
    resources :jobs, only: :index do
      get "getjob", on: :member

      collection do
        get "tango_status"
        get "tango_data"
      end
    end
    resources :announcements, except: :show
    resources :attachments

    resources :assessments, param: :name, except: :update do
      resource :autograder, except: [:new, :show]
      resources :assessment_user_data, only: [:edit, :update]
      resources :attachments
      resources :extensions, only: [:index, :create, :destroy]
      resources :groups, except: :edit do
        member do
          post "add"
          post "join"
          post "leave"
        end

        post "import", on: :collection
      end
      resources :problems, except: [:index, :show]
      resource :scoreboard, except: [:new] do
        get "help", on: :member
      end
      resources :submissions do
        resources :annotations, only: [:create, :update, :destroy]
        resources :scores, only: [:create, :show, :update]

        member do
          get "destroyConfirm"
          get "download"
          get "listArchive", as: :list_archive
          get "view"
        end

        collection do
          get "downloadAll"
          get "missing"
        end
      end

      member do
        match "bulkGrade", via: [:get, :post]
        post "bulkGrade_complete"
        get "bulkExport"
        get "releaseAllGrades"
        get "releaseSectionGrades"
        get "viewFeedback"
        get "reload"
        get "statistics"
        get "withdrawAllGrades"
        get "export"
        patch "edit/*active_tab", action: :update
        get "edit/*active_tab", action: :edit
        post "handin"
        get "history"
        get "viewGradesheet"
        get "writeup"
        get "handout"

        # autograde actions
        post "autograde_done"
        post "regrade"
        post "regradeBatch"
        post "regradeAll"

        # SVN actions
        get "admin_svn"
        post "import_svn"
        post "set_repo"

        # gradesheet ajax actions
        post "quickSetScore"
        post "quickSetScoreDetails"
        get "quickGetTotal"
        get "score_grader_info"
        get "submission_popover"

        # remote calls
        match "local_submit", via: [:get, :post]
        get "log_submit"
      end

      collection do
        get "installAssessment"
        post "importAssessment"
        post "importAsmtFromTar"
      end
    end

    resources :course_user_data do
      resource :gradebook, only: :show do
        get "bulkRelease"
        get "csv"
        get "invalidate"
        get "statistics"
        get "student"
        get "view"
      end

      member do
        get "destroyConfirm"
        match "sudo", via: [:get, :post]
        get "unsudo"
      end
    end

    member do
      get "bulkRelease"
      get "downloadRoster"
      match "email", via: [:get, :post]
      get "manage"
      get "moss"
      get "reload"
      match "report_bug", via: [:get, :post]
      post "runMoss"
      get "sudo"
      match "uploadRoster", via: [:get, :post]
      get "userLookup"
      get "users"
    end
  end
end

app/controllers/course_user_data_controller.rb
class CourseUserDataController < ApplicationController
  before_action :add_users_breadcrumb

    rescue_from ActionView::MissingTemplate do |exception|
      redirect_to("/home/error_404")
  end

  action_auth_level :index, :student
  def index
    @requestedUser = @cud
    render action: :show
  end

  action_auth_level :new, :instructor
  def new
    @newCUD = @course.course_user_data.new
    @newCUD.user = User.new
    @newCUD.tweak = Tweak.new
  end

  action_auth_level :create, :instructor
  def create
    cud_parameters = cud_params
    @newCUD = @course.course_user_data.new(cud_parameters)

    # check user existence
    email = cud_parameters[:user_attributes][:email]
    user = User.where(email: email).first
    if user.nil?
      user = User.roster_create(email,
                                cud_parameters[:user_attributes][:first_name],
                                cud_parameters[:user_attributes][:last_name],
                                "", "", "")

      if user
        @newCUD.user = user
      else
        if cud_parameters[:user_attributes][:email] == "" or
           cud_parameters[:user_attributes][:first_name] == "" or
           cud_parameters[:user_attributes][:last_name] == ""

          flash[:error] = "All required fields must be filled"
          redirect_to(action: "new") && return
        else
          flash[:error] = "The user with email #{email} could not be created"
          redirect_to(action: "new") && return
        end
      end

    else
      unless user.course_user_data.where(course: @course).empty?
        flash[:error] = "User #{email} is already in #{@course.full_name}"
        redirect_to(action: "new") && return
      end
      @newCUD.user = user
    end

    if @newCUD.save
      flash[:success] = "Success: added user #{email} in #{@course.full_name}"
      if @cud.user.administrator?
        redirect_to([:users, @course]) && return
      else
        redirect_to(action: "new") && return
      end
    else
      flash[:error] = "Adding user failed. Check all fields"
      redirect_to(action: "new") && return
    end
  end

  action_auth_level :show, :student
  def show
    @requestedUser = @cud.course.course_user_data.find(params[:id])
    respond_to do |format|
      if @requestedUser
        format.html
        format.json { render json: @requestedUser.to_json }
      else
        format.json { head :bad_request }
      end
    end
  end

  action_auth_level :edit, :student
  def edit
    @editCUD = @course.course_user_data.find(params[:id])
    if @editCUD.nil?
      flash[:error] = "Can't find user in the course."
      redirect_to(action: "index") && return
    end

    if (@editCUD.id != @cud.id) && (!@cud.instructor?) &&
       (!@cud.user.administrator?)
      flash[:error] = "Permission denied."
      redirect_to(action: "index") && return
    end

    @editCUD.tweak ||= Tweak.new
  end

  action_auth_level :update, :student
  def update
    # ensure presence of nickname
    # isn't a User model validation since users can start off without nicknames
    # application_controller's authenticate_user redirects here if nickname isn't set
    @editCUD = @course.course_user_data.find(params[:id])
    redirect_to(action: "index") && return if @editCUD.nil?

    if @cud.student?
      if (@editCUD.id != @cud.id)
        redirect_to(action: :index) && return
      else
        @editCUD.nickname = params[:course_user_datum][:nickname]
        if @editCUD.save
          redirect_to(action: :show) && return
        else
          flash[:error] = "Please complete all of your account information before continuing:"
          @editCUD.errors.full_messages.each do |msg|
            flash[:error] += "<br>#{msg}"
          end
          redirect_to(action: :edit) && return
        end
      end
    end

    # editor is not a student at this point
    # won't have tweak attributes if student is editing
    tweak_attrs = params[:course_user_datum][:tweak_attributes]
    if tweak_attrs && tweak_attrs[:value].blank?
      params[:course_user_datum][:tweak_attributes][:_destroy] = true
    end

    # When we're finished editing, go back to the user table
    if @editCUD.update(edit_cud_params)
      flash[:success] = "Success: Updated user #{@editCUD.email}"
      redirect_to([@course, @editCUD]) && return
    else
      flash[:error] = "Update failed. Check all fields"
      redirect_to(action: :edit) && return
    end
  end

  action_auth_level :destroy, :instructor
  def destroy
    @destroyCUD = @course.course_user_data.find(params[:id])
    if @destroyCUD && @destroyCUD != @cud && params[:yes1] && params[:yes2] && params[:yes3]
      @destroyCUD.destroy # awwww!!!
    end
    redirect_to([:users, @course]) && return
  end

  # Non-RESTful paths below

  # this GET page confirms that the instructor wants to destroy the user
  action_auth_level :destroyConfirm, :instructor
  def destroyConfirm
    @destroyCUD = @course.course_user_data.find(params[:id])
  end

  action_auth_level :sudo, :instructor
  def sudo
    redirect_to([@cud.course]) && return unless @cud.can_sudo? || session[:sudo]

    return unless request.post?

    sudo_user = User.where(email: params[:sudo_email]).first
    unless sudo_user
      flash[:error] = "User #{params[:sudo_email]} does not exist."
      redirect_to([@cud.course]) && return
    end

    sudo_cud = @course.course_user_data.where(user_id: sudo_user.id).first
    unless sudo_cud
      flash[:error] = "User #{params[:sudo_email]} does not exist."
      redirect_to([@cud.course]) && return
    end

    unless @cud.can_sudo_to?(sudo_cud)
      flash[:error] = "You do not have the privileges to act as " \
              "#{sudo_cud.display_name}."
      redirect_to([@cud.course]) && return
    end

    if @cud.id == sudo_cud.id
      flash[:error] = "There's no point in trying to act as yourself."
      redirect_to([@cud.course]) && return
    end

    session[:sudo] = {}
    session[:sudo][:user_id] = sudo_cud.user.id
    session[:sudo][:course_id] = sudo_cud.course.id

    # this was sudo_cud.display_name
    session[:sudo][:actual_name] = @cud.display_name

    redirect_to([@cud.course]) && return
  end

  action_auth_level :unsudo, :student
  def unsudo
    session[:sudo] = nil
    redirect_to([@cud.course]) && return
  end

private

  def add_users_breadcrumb
    if @cud.instructor
      @breadcrumbs << (view_context.link_to "Users", [:users, @course])
    end
  end

  def cud_params
    if @cud.administrator?
      params.require(:course_user_datum).permit(:school, :major, :year,
                                                :lecture, :section, :instructor, :dropped, :nickname, :course_assistant,
                                                user_attributes: [:first_name, :last_name, :email],
                                                tweak_attributes: [:_destroy, :kind, :value])
    elsif @cud.instructor?
      params.require(:course_user_datum).permit(:school, :major, :year,
                                                :lecture, :section, :instructor, :dropped, :nickname, :course_assistant,
                                                user_attributes: [:email, :first_name, :last_name],
                                                tweak_attributes: [:_destroy, :kind, :value])
    else
      params.require(:course_user_datum).permit(:nickname) # ,
      #        user_attributes: [:first_name, :last_name])
    end
  end

  def edit_cud_params
    if @cud.administrator?
      params.require(:course_user_datum).permit(:school, :major, :year,
                                                :lecture, :section, :instructor, :dropped, :nickname, :course_assistant,
                                                user_attributes: [:id, :email, :first_name, :last_name],
                                                tweak_attributes: [:_destroy, :kind, :value])
    elsif @cud.instructor?
      params.require(:course_user_datum).permit(:school, :major, :year,
                                                :lecture, :section, :instructor, :dropped, :nickname, :course_assistant,
                                                user_attributes: [:id, :email, :first_name, :last_name],
                                                tweak_attributes: [:_destroy, :kind, :value])
    else
      params.require(:course_user_datum).permit(:nickname) # user_attributes: [:first_name, :last_name])
    end
  end
end

app/views/course_user_data/_fields.html.erb
<%= f.fields_for :user, cud.user do |u| %>
    <%= u.email_field :email, disabled: false, placeholder: "johndoe@example.com" %>

    <%= u.text_field :first_name, disabled: false, placeholder: "John" %>
    <%= u.text_field :last_name, disabled: false, placeholder: "Doe" %>

  <% end %>

  <%= f.text_field :nickname, help_text: "Anonymizing nickname to display on the public scoreboards", placeholder: "batman" %>

  <%= isDisabled = false
      if !@cud.instructor? then
        isDisabled = true
      end
        f.text_field :lecture, help_text: "The lecture number", placeholder: "15213", disabled: isDisabled %>

  <%= isDisabled = false
      if !@cud.instructor? then
        isDisabled = true
      end
        f.text_field :section, help_text: "A course assistant can see the gradebook and bulk-release grades for their assigned lecture and section.", placeholder: "A", disabled: isDisabled %>

  <% if @cud.instructor? then %>

  <tr>
    <th>Course average tweak:</th>
    <td>
    <%= f.fields_for :tweak, cud.tweak do |t| %>
      <%= t.text_field :value, size: 18, value: "0", placeholder: "0"%>
      <%= t.select :kind, options_for_select({"points" => "points", "%" => "percent"}, :selected => (cud.tweak ? cud.tweak.kind : "points")) %>
    <% end %>
    </td>
    <td class="smallText">A tweak is a positive or negative value that adjusts the student's course average.<br>Ex: A tweak of 5 points would increase the student's course average by 5 points. </td>
  </tr>

	<%= f.check_box :dropped, help_text: "Dropping a student from a course prevents them from handing in submissions or downloading assessments. Additionally they do not appear in any gradebook. None of their account information or submissions are deleted." %>
  
  <%= f.check_box :instructor, help_text: "Instructors have full read/write access to the course." %>

  <%= f.check_box :course_assistant, help_text: "Course assistants can assign scores to problems and nothing else." %>

  <% end %>

app/views/course_user_data/edit.html.erb
<% @title = "Editing Enrollment for " + @editCUD.user.full_name %>

<% content_for :javascripts do %>
  <script type="application/javascript">
    function formvalidation(form){
      function DoubleByte(str) {
        for (var i = 0, n = str.length; i < n; i++) {
          if (str[i].charCodeAt() > 127) { return true; }
        }
        return false;
      }
      var formlog = 'Your nickname ';
      function flag(msg, nickname){
        nickname.setAttribute('style','background-color:#FFF352');
        if (formlog!= 'Your nickname '){formlog+=' and ';}
        formlog +=msg;

        nickname.focus();
      }
      var nickname = document.getElementById('user_nickname');
      var approve = true;

      if (nickname.value.length>20){approve = false; flag('is too long',nickname);}
      if (DoubleByte(nickname.value)===true){approve = false; flag('has non-ASCII characters',nickname);}

      if (approve){
        form.submit();
      } else {
        alert(formlog);
      }
    }
  </script>
<% end %>

<br>
<h2>Editing <%= @editCUD.user.full_name %>'s Enrollment in <%= @course.display_name %></h2>

<%= form_for @editCUD, url: course_course_user_datum_path(@course, @editCUD), builder: FormBuilderWithDateTimeInput do |f| %>
<% if @editCUD.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(@editCUD.errors.count, "error") %>
      prohibited the data from being saved:</h2>

		<ul>
			<% @editCUD.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

  <br><br>
  <%= render partial: "fields", locals: {f: f, cud: @editCUD} %>

  <br>
  <br>
  <input id="user_submit" name="commit" type="submit" class="btn primary" value="Save Changes" onclick="formvalidation(this.parentNode); return false;">
  <!--<%= f.submit 'Save Changes' , {:class=>""} %>-->

<%end %>

app/views/course_user_data/index.html.erb
<h3>Account Details for <%= @user.andrewID %></h3>
<table class="noStyle" >
<tr><td>Name</td><td><td> <%= @user.first_name %> <%= @user.last_name %> </td></tr>
<tr><td class="noStyle" >First Name</td><td class="noStyle"><%= @user.first_name %></td></tr>
<tr><td class="noStyle" >Last Name</td><td class="noStyle"><%= @user.last_name %></td></tr>
<tr><td class="noStyle" >andrewID</td><td class="noStyle"><%= @user.andrewID %></td></tr>
<tr><td class="noStyle">Email</td><td class="noStyle"><%= @user.email %></td></tr>
<tr><td class="noStyle">School</td><td class="noStyle"><%= @user.school %></td></tr>
<tr><td class="noStyle">Major</td><td class="noStyle"><%= @user.major %></td></tr>
<tr><td class="noStyle">Year</td><td class="noStyle"><%= @user.year %></td></tr>
<tr><td class="noStyle">Lecture</td><td class="noStyle"><%= @user.lecture %></td></tr>
<tr><td class="noStyle">Recitation</td><td class="noStyle"><%= @user.section %></td></tr>
<tr><td class="noStyle">Course</td><td class="noStyle"><%= @user.course.display_name %></td></tr>
</table>
<%= link_to 'Edit this information' , :action=>"edit", :id=>@user.id %>

app/views/course_user_data/new.html.erb
<% content_for :javascripts do %>
  <script type="application/javascript">
    $("#course_user_datum_user_attributes_email").on('change', userLookup);
    $("#course_user_datum_user_attributes_email").on('input', userLookup);
    /**
     * this AJAX function does an LDAP lookup on the partially-entered user email.
     **/
    function userLookup() {
      var email_input = document.getElementById("course_user_datum_user_attributes_email").value;
      if (!email_input || email_input == "") return;
      $.get('<%= url_for [:userLookup, @course, remote: true]  %>',  { email: email_input }, function( data ) {
        if (!data)  {
          $('#course_user_datum_user_attributes_first_name').prop('disabled', false);
          $('#course_user_datum_user_attributes_last_name').prop('disabled', false);
          // $('#course_user_datum_user_attributes_first_name').focus();
          $('#course_user_datum_user_attributes_first_name').val("");
            $('#course_user_datum_user_attributes_last_name').val("");
          return;
        }
        else {
          $('#course_user_datum_user_attributes_first_name').val(data.first_name);
          $('#course_user_datum_user_attributes_first_name').prop('disabled', true);
          $('#course_user_datum_user_attributes_last_name').val(data.last_name);
          $('#course_user_datum_user_attributes_last_name').prop('disabled', true);
          // $('#course_user_datum_nickname').focus();
        }
      });
    }
  </script>
<% end %>

<% @title="Enroll User" %>

<h2>Enroll User in <%= @course.display_name %></h2>

<br>

<%= form_for @newCUD, url: course_course_user_data_path, builder: FormBuilderWithDateTimeInput do |f| %>

<% if @newCUD.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(@newCUD.errors.count, "error") %>
      prohibited the data from being saved:</h2>

		<ul>
			<% @newCUD.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

  <%= render partial: "fields", locals: {f: f, cud: @newCUD} %>

  <br>
  <input id="user_submit" class="btn primary"name="commit" type="submit" value="Save Changes" onclick="formvalidation(this.parentNode); return false;">

<% end %>

app/views/course_user_data/show.html.erb
<h2><%= @requestedUser.first_name %> <%= @requestedUser.last_name %> (<%= @requestedUser.nickname %>)</h2>
<ul class="gray-box">
  <li><b>Contact</b><br>
    <a href="mailto:<%= @requestedUser.email %>"><%= @requestedUser.email %></a></li>
  <li> <b>About</b><br>
    Lecture <strong><%= @requestedUser.lecture %></strong><br>
    Section <strong><%= @requestedUser.section %></strong><br>
    Course <strong><%= @requestedUser.course.full_name %></strong><br>
    <%= @requestedUser.school %> <%= @requestedUser.major %>, Class of <%= @requestedUser.year %></li>
  <% if @cud.instructor? then %>
  <li><b>Course Average Tweak</b> of <%=raw tweak(@requestedUser.tweak) %></li>
  <% end %>
</ul>
<% if @cud.instructor? then %>
  <%= link_to raw('<span class="btn primary">Edit Information</span>'), edit_course_course_user_datum_path(@course, @requestedUser) %>
<% end %>

app/views/course_user_data/sudo.html.erb
<h2>Act as User</h2>

<p>You can use sudo to examine how Autolab appears to other users. You can also change your permission levels to see what your course assistants or students generically see.</p>

<p>
<%= form_tag do %>
  Act as user (email): <%= email_field_tag :sudo_email %>
  <%= submit_tag "Sudo", {:value=>"Sudo", :class=> "btn primary"} %>
<% end %>
</p>

app/views/course_user_data/user.html.erb
<h2><%= @requestedUser.first_name %> <%= @requestedUser.last_name %> (<%= @requestedUser.nickname %>)</h2>
<ul class="gray-box">
  <li><b>Contact</b><br>
    <%= @requestedUser.andrewID %> (andrewid)<br>
    <a href="mailto:<%= @requestedUser.email %>"><%= @requestedUser.email %></a></li>
  <li> <b>About</b><br>
    Lecture <strong><%= @requestedUser.lecture %></strong><br>
    Section <strong><%= @requestedUser.section %></strong><br>
    Course <strong><%= @requestedUser.course.display_name %></strong><br>
    <%= @requestedUser.school %> <%= @requestedUser.major %>, Class of <%= @requestedUser.year %></li>
  <% if @user.instructor? then %>
  <li><b>Course Average Tweak</b> of <%=raw tweak(@requestedUser.tweak) %></li>
  <% end %>
</ul>
<% if @user.instructor? then %>
  <%= link_to raw('<span class="btn primary">Edit Information</span>'), edit_course_user_path(@course, @requestedUser), :id=>@requestedUser.id %>
<% end %>