config/routes.rb
Autolab3::Application.routes.draw do
  root "courses#index"

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks",
                                    registrations:      "registrations" },
                     path_prefix: "auth"

  get "contact", to: "home#contact"

  namespace :home do
    if Rails.env == "development"
      match "developer_login", via: [:get, :post]
    end
    get "error"
    get "error_404"
    get "no_user"
  end

  resource :admin do
    match "email_instructors", via: [:get, :post]
  end

  resources :users do
    get "admin"
  end

  resources :courses, param: :name do
    resources :schedulers
    resources :jobs, only: :index do
      get "getjob", on: :member

      collection do
        get "tango_status"
        get "tango_data"
      end
    end
    resources :announcements, except: :show
    resources :attachments

    resources :assessments, param: :name, except: :update do
      resource :autograder, except: [:new, :show]
      resources :assessment_user_data, only: [:edit, :update]
      resources :attachments
      resources :extensions, only: [:index, :create, :destroy]
      resources :groups, except: :edit do
        member do
          post "add"
          post "join"
          post "leave"
        end

        post "import", on: :collection
      end
      resources :problems, except: [:index, :show]
      resource :scoreboard, except: [:new] do
        get "help", on: :member
      end
      resources :submissions do
        resources :annotations, only: [:create, :update, :destroy]
        resources :scores, only: [:create, :show, :update]

        member do
          get "destroyConfirm"
          get "download"
          get "listArchive", as: :list_archive
          get "view"
        end

        collection do
          get "downloadAll"
          get "missing"
        end
      end

      member do
        match "bulkGrade", via: [:get, :post]
        post "bulkGrade_complete"
        get "bulkExport"
        get "releaseAllGrades"
        get "releaseSectionGrades"
        get "viewFeedback"
        get "reload"
        get "statistics"
        get "withdrawAllGrades"
        get "export"
        patch "edit/*active_tab", action: :update
        get "edit/*active_tab", action: :edit
        post "handin"
        get "history"
        get "viewGradesheet"
        get "writeup"
        get "handout"

        # autograde actions
        post "autograde_done"
        post "regrade"
        post "regradeBatch"
        post "regradeAll"

        # SVN actions
        get "admin_svn"
        post "import_svn"
        post "set_repo"

        # gradesheet ajax actions
        post "quickSetScore"
        post "quickSetScoreDetails"
        get "quickGetTotal"
        get "score_grader_info"
        get "submission_popover"

        # remote calls
        match "local_submit", via: [:get, :post]
        get "log_submit"
      end

      collection do
        get "installAssessment"
        post "importAssessment"
        post "importAsmtFromTar"
      end
    end

    resources :course_user_data do
      resource :gradebook, only: :show do
        get "bulkRelease"
        get "csv"
        get "invalidate"
        get "statistics"
        get "student"
        get "view"
      end

      member do
        get "destroyConfirm"
        match "sudo", via: [:get, :post]
        get "unsudo"
      end
    end

    member do
      get "bulkRelease"
      get "downloadRoster"
      match "email", via: [:get, :post]
      get "manage"
      get "moss"
      get "reload"
      match "report_bug", via: [:get, :post]
      post "runMoss"
      get "sudo"
      match "uploadRoster", via: [:get, :post]
      get "userLookup"
      get "users"
    end
  end
end

app/models/attachment.rb
##
# Attachments are Course or Assessment specific, and allow instructors to
# handout files to students through Autolab.
#
class Attachment < ActiveRecord::Base
  validates :name, presence: true
  validates :filename, presence: true

  belongs_to :course
  belongs_to :assessment

  def file=(upload)
    directory = "attachments"
    filename = File.basename(upload.original_filename)
    path = Rails.root.join(directory, filename)
    addendum = 1

    # Deal with duplicate filenames on disk
    while File.exist?(path)
      path = Rails.root.join(directory, "#{filename}.#{addendum}")
      addendum += 1
    end
    self.filename = File.basename(path)
    File.open(path, "wb") { |f| f.write(upload.read) }
    self.mime_type = upload.content_type
  end

  def after_create
    COURSE_LOGGER.log("Created Attachment #{id}:#{filename} (#{mime_type}) as \"#{name}\")")
  end
end

app/controllers/attachments_controller.rb
##
# Attachments can be either assessment or course-specific.
# This controller handles both types, setting @is_assessment to distinguish the two
#
class AttachmentsController < ApplicationController
  # inherited from ApplicationController
  # this will also set an @is_assessment variable based on the result of is_assessment?
  before_action :set_assessment, if: :assessment?
  before_action :set_attachment, except: [:index, :new, :create]
  before_action :add_attachments_breadcrumb

    rescue_from ActionView::MissingTemplate do |exception|
      redirect_to("/home/error_404")
  end

  action_auth_level :index, :instructor
  def index
    @attachments = (@is_assessment) ? @assessment.attachments : @course.attachments
  end

  action_auth_level :new, :instructor
  def new
    @attachment = Attachment.new
  end

  action_auth_level :create, :instructor
  def create
    if @is_assessment
      @attachment = @course.attachments.new(assessment_id: @assessment.id)
    else
      @attachment = @course.attachments.new
    end

    update
  end

  action_auth_level :show, :student
  def show
    unless @attachment
      flash[:error] = "Could not find Attachment # #{params[:id]}"
      redirect_to([@course, :attachments]) && return
    end
    filename = Rails.root.join("attachments", @attachment.filename)
    unless File.exist?(filename)
      flash[:error] = "Error loading #{@attachment.name} from #{@attachment.filename}"
      redirect_to([@course, :attachments]) && return
    end
    send_file(filename, disposition: "inline",
                        type: @attachment.mime_type, filename: @attachment.filename) && return
  end

  action_auth_level :edit, :instructor
  def edit
  end

  action_auth_level :update, :instructor
  def update
    if @attachment.update(attachment_params)
      if @is_assessment
        redirect_to([@course, @assessment]) && return
      else
        redirect_to([@course, :attachments]) && return
      end
    else
      if @is_assessment
        redirect_to([:edit, @course, @assessment, @attachment]) && return
      else
        redirect_to([:edit, @course, @attachment]) && return
      end
    end
  end

  action_auth_level :destroy, :instructor
  def destroy
    @attachment.destroy
    if @is_assessment
      redirect_to([@course, @assessment]) && return
    else
      redirect_to([@course, :attachments]) && return
    end
  end

private

  def assessment?
    @is_assessment = params.key?(:assessment_name)
  end

  def set_attachment
    if @is_assessment
      @attachment = @course.attachments.find_by!(assessment_id: @assessment.id, id: params[:id])
    else
      @attachment = @course.attachments.find(params[:id])
    end
  end

  def add_attachments_breadcrumb
    if @is_assessment
      @breadcrumbs << (view_context.link_to "Assessment Attachments",
                                            [@course, @assessment, :attachments])
    else
      @breadcrumbs << (view_context.link_to "Course Attachments", [@course, :attachments])
    end
  end

  def attachment_params
    params.require(:attachment).permit(:name, :file, :released, :mime_type)
  end
end

app/views/attachments/_assessment_attachment.html.erb
<li>
  <%= link_to a.name, course_attachment_path(@course, a) %>  
  <% if @cud.instructor? then %>
    <% if attachment.assessment.nil? then %>
      <%= link_to 'Edit', [:edit, @course, attachment] %>
      <%= link_to 'Delete', [@course, attachment], method: :delete %>
    <% else %>
      <%= link_to 'Edit', [:edit, @course, attachment.assessment, attachment] %>
      <%= link_to 'Delete', [@course, attachment.assessment, attachment], method: :delete %>
    <% end %>
  <% end %>
</li>

app/views/attachments/_attachment.html.erb
<li class="collection-item">
  <p>
  <% if attachment.assessment.nil? then %>
    <i class="material-icons left">file_download</i>
    <%= link_to [@course, attachment] do %>
      <%= attachment.name %>
    <% end %>
  <% else %> 
    <%= link_to [@course, attachment.assessment, attachment] do %>
      <i class="material-icons left">file_download</i>
      <%= attachment.name %>
    <% end %>
  <% end %>

  <% if !attachment.assessment.nil? && @assessment.nil? then %>
    (<%= attachment.assessment.display_name %>)
  <% end %>

  <span class="secondary-content">
  <% if @cud.instructor? then %>
    <% if attachment.assessment.nil? then %>
      <%= link_to '<i class="material-icons left">mode_edit</i>'.html_safe, [:edit, @course, attachment], {class:"small"} %>
      <%= link_to '<i class="material-icons left">delete</i>'.html_safe, [@course, attachment], {method: :delete, class:"small"} %>
    <% else %>
      <%= link_to '<i class="material-icons left">mode_edit</i>'.html_safe, [:edit, @course, attachment.assessment, attachment], {class:"small"} %>
      <%= link_to '<i class="material-icons left">delete</i>'.html_safe, [@course, attachment.assessment, attachment], {method: :delete, class:"small"} %>
    <% end %>
  <% end %>
  </span>
  </p>
</li>

app/views/attachments/_course_attachment.html.erb
<li>
  <%= link_to a.name, course_attachment_path(@course, a) %>  
  <% if @cud.instructor? then %>
    <% if attachment.assessment.nil? then %>
      <%= link_to 'Edit', [:edit, @course, attachment] %>
      <%= link_to 'Delete', [@course, attachment], method: :delete %>
    <% else %>
      <%= link_to 'Edit', [:edit, @course, attachment.assessment, attachment] %>
      <%= link_to 'Delete', [@course, attachment.assessment, attachment], method: :delete %>
    <% end %>
  <% end %>
</li>

app/views/attachments/_form.html.erb
<%= form_for @attachment, as: :attachment, url: path, builder: FormBuilderWithDateTimeInput do |f| %>
  <%= f.error_messages %>

	<%= f.text_field :name, :required => true %>

	<% if @attachment.new_record? %>
  <div class="row embedded-form">
    <label class="custom-file-upload">
			<span class="btn primary" id="upload_button">
				Attatchment ...
					<%= f.file_field :file, class: "upload_embedded" %>
			</span>
		</label>
		<input type="text" id="upload_file" readonly value="Select to Upload a File.">
  </div>
	<% else %>
		<%= f.text_field :mime_type,
				help_text: "Note: If you change the Mime type of a file, you might need to clear your browser's cache in order for you to see the change." %>
	<% end %>

<script>
    document.getElementById("attachment_file").onchange = function(e) {
        document.getElementById("upload_file").value = document.getElementById("attachment_file").value.split(/(\\|\/)/g).pop();
    }
</script>

  <%= f.check_box :released %>

  <%= f.submit(@attachment.new_record? ? "Save" : "Upload", class: "btn primary") %>
<% end %>

app/views/attachments/edit.html.erb
<% path = if @is_assessment
            course_assessment_attachment_path(@course, @attachment.assessment, @attachment)
          else
            course_attachment_path(@course, @attachment)
          end %>

<div class="row">
  <div class="col-md-6">
    <%= render partial: "form", locals: {path: path} %>
  </div>
</div>

app/views/attachments/index.html.erb
<% if @is_assessment then %> 
  <h2>Listing <%= link_to @assessment.display_name, [@course, @assessment] %> Attachments</h2>
<% else %>
  <h2>Listing <%= link_to @course.full_name, @course %> Attachments</h2>
<% end %>


<p>
  <% if @is_assessment then %>
    <%= link_to 'Add '+@assessment.display_name+' Attachment', new_course_assessment_attachment_path(@course, @assessment) %>
  <% else %>
    <%= link_to 'Add Course Attachment', new_course_attachment_path(@course) %>
  <% end %>
</p>

<% if @attachments.any? then  %>
  <ul>
    <%= render @attachments %>
  </ul>
<% else %>
  There are no attachments yet.
<% end %>

app/views/attachments/new.html.erb
<% path =
  if @is_assessment
    course_assessment_attachments_path(@course, @assessment)
  else
     course_attachments_path(@course)
  end %>

<div class="row">
  <div class="col-md-6">
    <%= render partial: "form", locals: {path: path} %>
  </div>
</div>