config/routes.rb
Autolab3::Application.routes.draw do
  root "courses#index"

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks",
                                    registrations:      "registrations" },
                     path_prefix: "auth"

  get "contact", to: "home#contact"

  namespace :home do
    if Rails.env == "development"
      match "developer_login", via: [:get, :post]
    end
    get "error"
    get "error_404"
    get "no_user"
  end

  resource :admin do
    match "email_instructors", via: [:get, :post]
  end

  resources :users do
    get "admin"
  end

  resources :courses, param: :name do
    resources :schedulers
    resources :jobs, only: :index do
      get "getjob", on: :member

      collection do
        get "tango_status"
        get "tango_data"
      end
    end
    resources :announcements, except: :show
    resources :attachments

    resources :assessments, param: :name, except: :update do
      resource :autograder, except: [:new, :show]
      resources :assessment_user_data, only: [:edit, :update]
      resources :attachments
      resources :extensions, only: [:index, :create, :destroy]
      resources :groups, except: :edit do
        member do
          post "add"
          post "join"
          post "leave"
        end

        post "import", on: :collection
      end
      resources :problems, except: [:index, :show]
      resource :scoreboard, except: [:new] do
        get "help", on: :member
      end
      resources :submissions do
        resources :annotations, only: [:create, :update, :destroy]
        resources :scores, only: [:create, :show, :update]

        member do
          get "destroyConfirm"
          get "download"
          get "listArchive", as: :list_archive
          get "view"
        end

        collection do
          get "downloadAll"
          get "missing"
        end
      end

      member do
        match "bulkGrade", via: [:get, :post]
        post "bulkGrade_complete"
        get "bulkExport"
        get "releaseAllGrades"
        get "releaseSectionGrades"
        get "viewFeedback"
        get "reload"
        get "statistics"
        get "withdrawAllGrades"
        get "export"
        patch "edit/*active_tab", action: :update
        get "edit/*active_tab", action: :edit
        post "handin"
        get "history"
        get "viewGradesheet"
        get "writeup"
        get "handout"

        # autograde actions
        post "autograde_done"
        post "regrade"
        post "regradeBatch"
        post "regradeAll"

        # SVN actions
        get "admin_svn"
        post "import_svn"
        post "set_repo"

        # gradesheet ajax actions
        post "quickSetScore"
        post "quickSetScoreDetails"
        get "quickGetTotal"
        get "score_grader_info"
        get "submission_popover"

        # remote calls
        match "local_submit", via: [:get, :post]
        get "log_submit"
      end

      collection do
        get "installAssessment"
        post "importAssessment"
        post "importAsmtFromTar"
      end
    end

    resources :course_user_data do
      resource :gradebook, only: :show do
        get "bulkRelease"
        get "csv"
        get "invalidate"
        get "statistics"
        get "student"
        get "view"
      end

      member do
        get "destroyConfirm"
        match "sudo", via: [:get, :post]
        get "unsudo"
      end
    end

    member do
      get "bulkRelease"
      get "downloadRoster"
      match "email", via: [:get, :post]
      get "manage"
      get "moss"
      get "reload"
      match "report_bug", via: [:get, :post]
      post "runMoss"
      get "sudo"
      match "uploadRoster", via: [:get, :post]
      get "userLookup"
      get "users"
    end
  end
end

app/controllers/gradebooks_controller.rb
require "association_cache"
require "csv"
require "statistics"
require "utilities"

class GradebooksController < ApplicationController
    rescue_from ActionView::MissingTemplate do |exception|
      redirect_to("/home/error_404")
  end
  action_auth_level :show, :student
  def show
    if @cud.instructor?
      redirect_to action: :view
    elsif @cud.course_assistant?
      redirect_to action: :view, section: @cud.section
    else
      redirect_to action: :student
    end
  end

  action_auth_level :view, :course_assistant
  def view
    @matrix = GradeMatrix.new @course, @cud
    @section = params[:section]

    permission = @cud.has_auth_level? :instructor
    @options = {
      linkify_andrew_ids: permission,
      render_excused_grade_type: permission,
      render_zeroed_grade_type: permission,
      show_actions: permission
    }

    unless @cud.has_auth_level?(:instructor) || @section == @cud.section
      flash[:error] = "You can't view other section gradebooks."
      redirect_to([@course]) && return
    end
  end

  action_auth_level :student, :student
  def student
    @_cud = params[:id] ?
              CourseUserDatum.find_by_id(params[:id]) : @cud

    if @_cud.nil?
      flash[:error] = "Can't find requested user course data."
      redirect_to(course_course_user_datum_gradebook_path) && return
    end

    unless @cud == @_cud || (@cud.instructor? && @cud.course == @_cud.course)
      if (@cud != @_cud)
        flash[:error] = "You can't view other students' gradebooks."
      else
        flash[:error] = "You can't view other classes' gradebooks."
      end
      redirect_to(course_course_user_datum_gradebook_path) && return
    end

    @categories_sorted = @course.assessment_categories
  end

  action_auth_level :csv, :instructor
  def csv
    @matrix = GradeMatrix.new @course, @cud

    csv = render_to_string layout: false
    send_data csv, filename: "#{@course.name}.csv"
  end

  action_auth_level :invalidate, :instructor
  def invalidate
    GradeMatrix.invalidate @course
    redirect_to action: :show
  end

  action_auth_level :statistics, :instructor
  def statistics
    matrix = GradeMatrix.new @course, @cud
    cols = {}

    # extract assessment final scores
    @course.assessments.each do |asmt|
      next unless matrix.has_assessment? asmt.id

      cells = matrix.cells_for_assessment asmt.id
      final_scores = cells.map { |c| c["final_score"] }
      cols[asmt.name] = final_scores
    end

    # category averages
    @course.assessment_categories.each do |cat|
      next unless matrix.has_category? cat

      cols["#{cat} Average"] = matrix.averages_for_category cat
    end

    # course averages
    cols["Course Average"] = matrix.course_averages

    # calculate statistics
    @course_stats = {}
    stat = Statistics.new
    cols.each do |key, value|
      @course_stats[key] = stat.stats(value)
    end
  end

  action_auth_level :bulkRelease, :instructor
  def bulkRelease
    for assessment in @course.assessments do
      for problem in assessment.problems do
        scores = problem.scores.where(released: false)
        for score in scores do
          score.released = true
          score.save
        end
      end
    end
    redirect_to course_course_user_datum_gradebook_path(@course, @cud)
  end
end

app/helpers/gradebook_helper.rb
require "utilities"

module GradebookHelper
  def gradebook_columns(matrix, course)
    # user info columns
    columns = [
      { id: "number", name: "#", field: "", width: 50 },
      { id: "email", name: "Email", field: "email",
        sortable: true, width: 100, cssClass: "email",
        headerCssClass: "email" },
      { id: "first_name", name: "First", field: "first_name",
        sortable: true, width: 100, cssClass: "first_name",
        headerCssClass: "first_name" },
      { id: "last_name", name: "Last", field: "last_name",
        sortable: true, width: 100, cssClass: "last_name",
        headerCssClass: "last_name" },
      { id: "section", name: "Sec", field: "section",
        sortable: true, width: 50 }
    ]

    course.assessment_categories.each do |cat|
      next unless matrix.has_category? cat

      # assessment column
      course.assessments_with_category(cat).each do |asmt|
        next unless matrix.has_assessment? asmt.id

        columns << { id: asmt.name, name: asmt.display_name, field: asmt.name,
                     sortable: true, cssClass: "computed assessment_final_score",
                     headerCssClass: "assessment_final_score",
                     before_grading_deadline: matrix.before_grading_deadline?(asmt.id) }
      end

      # category average column
      columns << { id: cat, name: cat + " Average",
                   field: "#{cat}_category_average",
                   sortable: true, cssClass: "computed category_average",
                   headerCssClass: "category_average", width: 100 }
    end

    # course average column
    columns << { id: "average", name: "Average", field: "course_average",
                 sortable: true, width: 100, cssClass: "computed course_average",
                 headerCssClass: "course_average" }

    columns << { id: "email_right", name: "Email", field: "email",
                 sortable: true, width: 100, cssClass: "email right",
                 headerCssClass: "email right" }

    columns
  end

  def gradebook_rows(matrix, course, section = nil, lecture = nil)
    rows = []

    course.course_user_data.each do |cud|
      next unless matrix.has_cud? cud.id

      # if this is a section gradebook
      next unless cud.section == section if section

      next unless cud.lecture == lecture if lecture

      sgb_link = url_for controller: :gradebooks, action: :student, id: cud.id

      row = {}

      row["id"] = cud.id
      row["email"] = cud.user.email
      row["student_gradebook_link"] = sgb_link
      row["first_name"] = cud.user.first_name
      row["last_name"] = cud.user.last_name
      row["section"] = cud.section

      # TODO: formalize score render stack, consolidate with computed score
      course.assessments.ordered.each do |a|
        next unless matrix.has_assessment? a.id

        cell = matrix.cell(a.id, cud.id)
        row[a.name] = round cell["final_score"]
        row["#{a.name}_submission_status"] = cell["submission_status"]
        row["#{a.name}_grade_type"] = cell["grade_type"]
        row["#{a.name}_end_at"] = cell["end_at"]
      end

      course.assessment_categories.each do |cat|
        next unless matrix.has_category? cat

        key = "#{cat}_category_average"
        row[key] = round matrix.category_average(cat, cud.id)
      end

      row["course_average"] = round matrix.course_average(cud.id)

      rows << row
    end

    rows
  end

  def regenerate_url
    url_for controller: :gradebooks, action: :invalidate
  end

  def csv_header(matrix, course)
    header = %w(Email first_name last_name Lecture Section School Major Year)
    course.assessment_categories.each do |cat|
      next unless matrix.has_category? cat
      course.assessments_with_category(cat).each do |asmt|
        next unless matrix.has_assessment? asmt.id
        header << asmt.name
      end
      header << "#{cat} Average"
    end
    header << "Course Average"

    header
  end

  def formatted_status(status)
    case status
      when Float
        round status
      when String
        status
      else
        throw "FATAL: AUD status must be Float or String; was #{status.class}"
    end
  end

  def gradebook_csv(matrix, course)
    CSV.generate do |csv|
      csv << csv_header(matrix, course)

      course.course_user_data.each do |cud|
        next unless matrix.has_cud? cud.id

        # general info
        row = [cud.user.email, cud.user.first_name, cud.user.last_name, cud.lecture, cud.section, cud.school, cud.major, cud.year]

        # assessment status (see AssessmentUserDatum.status), category averages
        course.assessment_categories.each do |cat|
          next unless matrix.has_category? cat
          course.assessments_with_category(cat).each do |asmt|
            next unless matrix.has_assessment? asmt.id

            row << formatted_status(matrix.cell(asmt.id, cud.id)["status"])
          end

          row << round(matrix.category_average(cat, cud.id))
        end

        # course average
        row << round(matrix.course_average(cud.id))

        # add to csv
        csv << row
      end
    end
  end
end

app/views/gradebooks/csv.erb
<%= gradebook_csv @matrix, @course %>

app/views/gradebooks/statistics.html.erb
<% content_for :stylesheets do %>
  <%= stylesheet_link_tag "student_gradebook" %>
<% end %>

<div class="container-fluid">
  <h4>Course Statistics</h4>

  <div class="category">
    <table class="grades">
      <colgroup>
        <col class="asmt_names"></col>
        <col class="gdu"></col>
        <col class="gdu"></col>
        <col class="gdu"></col>
        <col class="gdu"></col>
        <col class="gdu"></col>
      </colgroup>
      <thead>
        <tr class="header">
          <th></th>
          <th>Mean</th>
          <th>Median</th>
          <th>Std. Dev.</th>
          <th>Min</th>
          <th>Max</th>
        </tr>
      </thead>
      <tbody>
      <% @course_stats.each do |name, stats| %>
        <tr>
          <td>
            <% # TODO: RESTORE LINKS %>
            <%= name %>
            <% # TODO: BAD! FIX! %>
            <% # name.end_with?(' Average') ? name : (link_to name, { :controller => name }, :class => :asmt_link) %>
          </td>
          <td><%= stats[:mean] %></td>
          <td><%= stats[:median] %></td>
          <td><%= stats[:stddev] %></td>
          <td><%= stats[:min] %></td>
          <td><%= stats[:max] %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/gradebooks/student.html.erb
<% content_for :head do %>
  <title>Grades for <%= @_cud.email %></title>
<% end %>

<% content_for :stylesheets do %>
  <%= stylesheet_link_tag "student_gradebook" %>
<% end %>

<% content_for :javascripts do %>
  <%= javascript_include_tag "initialize_tooltips" %>
<% end %>

<div class="gradebook">
  <h4>Grades for <%= @_cud.email %></h4>

  <% if not @course.gb_message.blank? %>
    <div class="gb_message"><%=raw(@course.gb_message)%></div>
  <% end %>

  <div class="grades_container">
    <% @categories_sorted.each_slice(2) do |cat_pair| %>
    <div class="row cat_pair">
      <% cat_pair.each do |cat| %>
        <div class="col m12 l6 cat_container">

        <div class="category">
          <table class="grades">
            <colgroup>
              <col class="asmt_names"></col>
              <% if @course.grace_days > 0 %>
                <col class="gdu"></col>
              <% end %>
              <col class="pld"></col>
              <col class="fs"></col>
            </colgroup>

            <tr class="header">
              <th class="cat_name"><%= cat %></th>
              <% if @course.grace_days > 0 %>
                <th>
                  GDU
                  <i class="material-icons tooltipped" data-html="true" data-tooltip="<b>Grace Days Used</b><br />Number of late days used for which <em>no</em> penalty was incurred">help</i>
                </th>
              <% end %>
              <th>
                PLD
                <i class="material-icons tooltipped" data-html="true" data-tooltip="<b>Penalty Late Days</b><br />Number of late days used for which a penalty was incurred">help</i>
              </th>
              <th>Final Score</th>
            </tr>
              <% @course.assessments_with_category(cat, @cud.student?).each do |asmt| %>
                <% aud = asmt.aud_for @_cud  %>
                <tr>
                  <td>
                    <span>
                    <%= link_to asmt.display_name, course_assessment_path(@course, asmt) %>
                    <% unless @cud.student? %>
                      <a class="history_icon" href="<%= history_url(@_cud, asmt) %>">
                        <i title="Handin history" class="icon-list tip"></i>
                      </a>
                  <% end %>
                </td>
                <% if @course.grace_days > 0 %>
                  <td><%= aud.grace_days_used %></td>
                <% end %>
                <td><%= aud.penalty_late_days %></td>
                <td>
                  <% case aud.grade_type
                     when AssessmentUserDatum::ZEROED %>
                    <% if @cud.instructor? %>
                      <span class="zeroed tooltipped" data-tooltip="This final score has been zeroed out.">
                        <%= render_final_score aud %>
                      </span>
                    <% else %>
                      <%= render_final_score aud %>
                    <% end %>

                  <% when AssessmentUserDatum::EXCUSED %>
                    <% pronoun = @cud == @_cud ? "You" : @_cud.email %>
                    <% tip = "#{pronoun} has been excused from #{asmt.display_name}." %>
                    <span class="excused label label-info tooltipped" data-html="true" data-tooltip="<%= tip %>">
                      Excused
                    </span>

                  <% when AssessmentUserDatum::NORMAL %>
                    <% case aud.submission_status
                       when :submitted %>
                      <% if Time.now <= aud.assessment.grading_deadline %>
                        <i class="material-icons tooltipped" data-tooltip="Final score will be visible once grading is complete.">access_time</i>
                      <% else %>
                        <%= render_final_score aud %>
                      <% end %>

                    <% when :not_submitted %>
                      <% if Time.now <= aud.assessment.grading_deadline %>
                        <i class="material-icons tooltipped" data-tooltip="No submission was made.">priority_high</i>
                      <% else %>
                        <span class="not-submitted tooltipped" data-tooltip="No submission was made.">
                          <%= render_final_score aud %>
                        </span>
                      <% end %>

                    <% when :not_yet_submitted %>
                      <% if Time.now <= aud.assessment.grading_deadline %>
                        <i class="material-icons tooltipped" data-tooltip="No submission has been made yet.">priority_high</i>
                      <% else %>
                        <span class="not-yet-submitted tooltipped" data-tooltip="No submission has been made yet.">
                          <%= render_final_score aud %>
                        </span>
                      <% end %>
                    <% end %>
                  <% end %>
                </td>
              </tr>
            <% end %>
            <tr class="footer">
              <th>Category Average</th>
              <% if @course.grace_days > 0 %><th></th><% end %>
              <th></th>
              <th class="cat_avg"><%= computed_score { @_cud.category_average cat, @cud } %></td>
            </tr>
          </table>
        </div>

        </div> <!-- span -->
      <% end %> <!-- cat -->
    </div> <!-- row -->
    <% end %> <!-- cat_pair -->

    <div class="course">
      <table>
        <% if @cud.instructor? %>
        <tr>
          <th>Average Tweak</th>
          <td><%= link_to raw(tweak(@_cud.tweak)), [:edit, @course, @_cud] %></td>
        </tr>
        <% elsif @_cud.tweak %>
        <tr>
          <th>Average Tweak</th>
          <td><%== tweak @_cud.tweak %></td>
        </tr>
        <% end %>
        <tr>
          <th>Course Average</th>
          <td><%== computed_score { @_cud.average @cud } %></td>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/gradebooks/view.html.erb
<% @title = "Gradebook" %>

<% content_for :stylesheets do %>
  <%= stylesheet_link_tag "instructor_gradebook" %>
  <%= stylesheet_link_tag "SlickGrid/2.02/slick.grid.css" %>
  <%= stylesheet_link_tag "SlickGrid/2.02/controls/slick.columnpicker.css" %>
  <%= stylesheet_link_tag "icons" %>

  <!-- Temporary Bootstrap overrides -->
  <style type="text/css">
    *, *:before, *:after {
      -moz-box-sizing: content-box;
           box-sizing: content-box;
    }
    div#pageBody {
      width: 95%;
      margin: 0 auto;
      padding: 15px;
      box-sizing: border-box;
    }

    h1#courseTitle {
      font-size: 24.5px;
      margin-bottom: 0;
    }

    span.label {
      text-transform: uppercase;
      font-size: 8.5px;
      vertical-align: text-bottom;
    }

    .slick-cell img {
      vertical-align: baseline;
    }

    input#filter {
      margin-bottom: 0;
    }

    #gradebook {
      font-size: 12px;
    }

    input {
      font-size: inherit !important;
    }

    div#footer {
      display: none;
    }

    <% unless @options[:show_actions] %>
      div#filter_container {
        margin-bottom: 20px;
      }
    <% end %>
  </style>
<% end %>


<% content_for :js_widget_patch do %>
  <%= external_javascript_include_tag "jquery-ui", "1.10.2" %>
  <%# jQuery UI is required for SlickGrid, but Bootstrap provides a tooltip plugin %>
  <%# The following must come after jQuery UI but before Bootstrap 3 is loaded %>
  <%# to resolve namespace issues %>
  <script>
    $.widget.bridge('uitooltip', $.ui.tooltip);
  </script>
<% end %>

<% content_for :javascripts do %>
  <%= javascript_include_tag "jquery.event.drag-2.2.js" %>
  <%= javascript_include_tag "SlickGrid/2.02/slick.core.js" %>
  <%= javascript_include_tag "SlickGrid/2.02/slick.grid.js" %>
  <%= javascript_include_tag "SlickGrid/2.02/slick.dataview.js" %>
  <%= javascript_include_tag "SlickGrid/2.02/controls/slick.columnpicker.js" %>

  <script type="text/javascript">
    var columns = <%== gradebook_columns(@matrix, @course).to_json %>
    var data = <%== gradebook_rows(@matrix, @course, @section).to_json %>
    var options = <%== @options.to_json %>
  </script>

  <%= javascript_include_tag "gradebook" %>
<% end %>

<% if not @course.gb_message.blank? %>
  <div class="gb_message"><%=raw(@course.gb_message)%></div>
<% end %>

<div class="row">
  <div class="input-field col s4 offset-s4 filter_container">
    <i class="material-icons prefix">search</i>
    <input id="filter" placeholder="Search..." type="text"></input>
  </div>
</div>

<% if @options[:show_actions] %>
  <div id="last_updated">
    <a class="tip link" title="Export as CSV" href="<%= url_for :action => :csv %>">
      Export
    </a> /
    <a class="tip link" title="Course Statistics" href="<%= url_for :action => :statistics %>">
      Statistics
    </a> /
    <a class="tip regenerate" title="Regenerate (~10 seconds)" href="<%= url_for :action => :invalidate %>">
      <i class="icon-refresh"></i>
      <%= time_ago_in_words(DateTime.parse @matrix.last_updated) %> old
    </a>
  </div>
<% end %>

<div id="gradebook">
  <!-- will be filled in by gradebook.js -->
</div>